package com.cupster.database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cupster.database.model.TodayInfo;
import com.cupster.database.model.HistoryInfo;
import com.cupster.database.model.LifeIndexInfo;
import com.cupster.database.model.Pm25Info;
import com.cupster.database.model.WeekInfo;

import com.cupster.database.dao.TodayInfoDao;
import com.cupster.database.dao.HistoryInfoDao;
import com.cupster.database.dao.LifeIndexInfoDao;
import com.cupster.database.dao.Pm25InfoDao;
import com.cupster.database.dao.WeekInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig todayInfoDaoConfig;
    private final DaoConfig historyInfoDaoConfig;
    private final DaoConfig lifeIndexInfoDaoConfig;
    private final DaoConfig pm25InfoDaoConfig;
    private final DaoConfig weekInfoDaoConfig;

    private final TodayInfoDao todayInfoDao;
    private final HistoryInfoDao historyInfoDao;
    private final LifeIndexInfoDao lifeIndexInfoDao;
    private final Pm25InfoDao pm25InfoDao;
    private final WeekInfoDao weekInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        todayInfoDaoConfig = daoConfigMap.get(TodayInfoDao.class).clone();
        todayInfoDaoConfig.initIdentityScope(type);

        historyInfoDaoConfig = daoConfigMap.get(HistoryInfoDao.class).clone();
        historyInfoDaoConfig.initIdentityScope(type);

        lifeIndexInfoDaoConfig = daoConfigMap.get(LifeIndexInfoDao.class).clone();
        lifeIndexInfoDaoConfig.initIdentityScope(type);

        pm25InfoDaoConfig = daoConfigMap.get(Pm25InfoDao.class).clone();
        pm25InfoDaoConfig.initIdentityScope(type);

        weekInfoDaoConfig = daoConfigMap.get(WeekInfoDao.class).clone();
        weekInfoDaoConfig.initIdentityScope(type);

        todayInfoDao = new TodayInfoDao(todayInfoDaoConfig, this);
        historyInfoDao = new HistoryInfoDao(historyInfoDaoConfig, this);
        lifeIndexInfoDao = new LifeIndexInfoDao(lifeIndexInfoDaoConfig, this);
        pm25InfoDao = new Pm25InfoDao(pm25InfoDaoConfig, this);
        weekInfoDao = new WeekInfoDao(weekInfoDaoConfig, this);

        registerDao(TodayInfo.class, todayInfoDao);
        registerDao(HistoryInfo.class, historyInfoDao);
        registerDao(LifeIndexInfo.class, lifeIndexInfoDao);
        registerDao(Pm25Info.class, pm25InfoDao);
        registerDao(WeekInfo.class, weekInfoDao);
    }
    
    public void clear() {
        todayInfoDaoConfig.clearIdentityScope();
        historyInfoDaoConfig.clearIdentityScope();
        lifeIndexInfoDaoConfig.clearIdentityScope();
        pm25InfoDaoConfig.clearIdentityScope();
        weekInfoDaoConfig.clearIdentityScope();
    }

    public TodayInfoDao getTodayInfoDao() {
        return todayInfoDao;
    }

    public HistoryInfoDao getHistoryInfoDao() {
        return historyInfoDao;
    }

    public LifeIndexInfoDao getLifeIndexInfoDao() {
        return lifeIndexInfoDao;
    }

    public Pm25InfoDao getPm25InfoDao() {
        return pm25InfoDao;
    }

    public WeekInfoDao getWeekInfoDao() {
        return weekInfoDao;
    }

}
